//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsViewer
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int folder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int folder_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int speech_balloon = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int CurrentPath = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int MainImage = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int MyButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int RowText = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int ZoomButtons = 2131034116;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DirectoryRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FileBrowser = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FileRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ParentRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Viewer = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
